// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildTree() {
  return window['go']['main']['App']['BuildTree']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetGitBranches(arg1) {
  return window['go']['main']['App']['GetGitBranches'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetPath() {
  return window['go']['main']['App']['GetPath']();
}

export function GetTerminalOutput(arg1) {
  return window['go']['main']['App']['GetTerminalOutput'](arg1);
}

export function GetTerminalSync() {
  return window['go']['main']['App']['GetTerminalSync']();
}

export function GoUp() {
  return window['go']['main']['App']['GoUp']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function LoadChildren(arg1) {
  return window['go']['main']['App']['LoadChildren'](arg1);
}

export function ReadTerminalOutput(arg1) {
  return window['go']['main']['App']['ReadTerminalOutput'](arg1);
}

export function SetPath(arg1) {
  return window['go']['main']['App']['SetPath'](arg1);
}

export function SetTerminalSync(arg1) {
  return window['go']['main']['App']['SetTerminalSync'](arg1);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInput'](arg1, arg2);
}
