// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {explorer} from '../models';

export function BuildTree():Promise<explorer.TreeNode>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string):Promise<void>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetGitBranches(arg1:string):Promise<Array<string>>;

export function GetGitStatus(arg1:string):Promise<string>;

export function GetPath():Promise<string>;

export function GetTerminalOutput(arg1:string):Promise<any>;

export function GetTerminalSync():Promise<boolean>;

export function GoUp():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function ListFiles():Promise<Array<explorer.FileInfo>>;

export function LoadChildren(arg1:string):Promise<Array<explorer.FileInfo>>;

export function ReadTerminalOutput(arg1:string):Promise<string>;

export function SetPath(arg1:string):Promise<void>;

export function SetTerminalSync(arg1:boolean):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
